### ISSUE TITLE
MacOS client missing

### ISSUE THREAD

**Issue by cjaentsch** [fiskaly/fiskaly-sdk-java#1]
The previous implementation also had a lib compiled for MacOS. Is that still in planning? We are developing on MacOS so now it's really hard to debug anything. Also some customers use MacOS to host their POS.

**Comment by prempador** [comment]
We are currently working on the compiled lib for MacOS and iOS. I will update this issue as soon as this is available!

**Comment by cjaentsch** [comment]
Alright, perfect! 👍

**Comment by cjaentsch** [comment]
Any news on this?

**Comment by prempador** [comment]
Will be released tomorrow with the 1.2.000 release
