### ISSUE TITLE
Impossible to download the export TAR file since the V1 update

### ISSUE THREAD

**Issue by ghost** [fiskaly/fiskaly-sdk-java#10]
Here is the JSON file I receive when i try to retrieve the TAR control file:
```
{
	"href": "https://kassensichv.io/api/v1/tss/19314bd6-307c-378b-96d2-822574db1da1/export/635e9b3a-b046-32a8-b46a-e60285f7e404/file/0459fd0b-1b50-4b37-a67a-5b9ff57357c8.tar",
	"state": "COMPLETED",
	"time_request": 1590224942,
	"time_start": 1590224944,
	"time_end": 1590225105,
	"tss_id": "19314bd6-307c-378b-96d2-822574db1da1",
	"metadata": {},
	"_type": "EXPORT",
	"_id": "635e9b3a-b046-32a8-b46a-e60285f7e404",
	"_env": "TEST",
	"_version": "1.0.0"
}
```

Everything looks fine, except :
- The generation time. It take about 2-5 minutes to generate the control file of the current day (with less than 10 transactions) 
- The generated link doesn't work. It fails directly, the download does not even start. I think there is a problem with the header.

**Comment by ghost** [comment]
I invite you to copy paste the following link into your browser : 
> https://kassensichv.io/api/v1/tss/19314bd6-307c-378b-96d2-822574db1da1/export/635e9b3a-b046-32a8-b46a-e60285f7e404/file/0459fd0b-1b50-4b37-a67a-5b9ff57357c8.tar

You will see the problem directly.

I remain at your disposal for more information

**Comment by ghost** [comment]
Did you manage to reproduce this issue ?

**Comment by cjaentsch** [comment]
Same here

**Comment by cjaentsch** [comment]
Seems to work right now.

**Comment by prempador** [comment]
We are working on making the exports more stable right now. Sorry for the inconvenience.

**Comment by prempador** [comment]
This should now work as expected, there will be another patch for the exports next week, but for now there shouldn't be any issues.
