### ISSUE TITLE
Mac dylib not found

### ISSUE THREAD

**Issue by cjaentsch** [fiskaly/fiskaly-sdk-java#17]
I get the following exception when trying to load the dylib for MacOS (v.1.2.000):

The path seems to be built incorrectly (double "dylib.dylib").

```
Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libcom.fiskaly.client-darwin-amd64-v1.2.000.dylib.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 34 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libcom.fiskaly.client-darwin-amd64-v1.2.000.dylib.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 34 more

```

**Comment by prempador** [comment]
Thanks, I just checked. We build the path correct, without the duplicate. Seems to be an issue somewhere else. 
I need to look into it some more.

**Comment by cjaentsch** [comment]
> Thanks, I just checked. We build the path correct, without the duplicate. Seems to be an issue somewhere else.
> I need to look into it some more.

Maybe on MacOS you don't need to add the ".dylib" when calling Native.register...

**Comment by prempador** [comment]
> > Thanks, I just checked. We build the path correct, without the duplicate. Seems to be an issue somewhere else.
> > I need to look into it some more.
> 
> Maybe on MacOS you don't need to add the ".dylib" when calling Native.register...

Tried that as well, didn't work.

**Comment by cjaentsch** [comment]
Ok, but you can reproduce it? So it's not an error just in our environment?

**Comment by prempador** [comment]
> Ok, but you can reproduce it? So it's not an error just in our environment?

Yes, I am able to reproduce, and I will work on a fix.

**Comment by cjaentsch** [comment]
Seems to be the libName not starting with "lib" triggers the following function in NativeLibrary.mapSharedLibraryName:
<img width="1132" alt="Bildschirmfoto 2020-06-16 um 17 03 00" src="https://user-images.githubusercontent.com/4006662/84791768-5b2fe280-aff3-11ea-9557-069349395f91.png">

... which leads the "name" to have another ".dylib" appended.
<img width="1192" alt="Bildschirmfoto 2020-06-16 um 17 03 25" src="https://user-images.githubusercontent.com/4006662/84791780-5f5c0000-aff3-11ea-93ab-dac8c7203a76.png">

**Comment by prempador** [comment]
Yep, just came to the same conclusion. But changing the dylib name just for JNA sounds kinda dirty to me.

**Comment by prempador** [comment]
But it looks like the problem kinda lies with Java itself. https://www.tutorialspoint.com/java/lang/system_maplibraryname.htm

**Comment by prempador** [comment]
I found a workaround for now. This would only work if the .dylib is in System.getProperty("user.dir").

``` Java 
static {
    String libName = getLibName();
    if (Platform.isMac()) {
      libName = System.getProperty("user.dir") + "/" + libName;
    }
    setLibSearchPath();
    Native.register(ClientLibrary.class, libName);
  }

**Comment by cjaentsch** [comment]
Strange JAVA behaviour... In our case the dylib is located in the "jna.library.path", so the workaround wouldn't work.

**Comment by prempador** [comment]
So, the workaround will be that we provide a .dylib specially for Java named "libcom.fiskaly.client-darwin-amd64-v1.2.000.dylib" and remove the dylib extension from our path builder. 
I tested this, and this works for sure. Expect changes by tomorrow or the day after.

**Comment by cjaentsch** [comment]
Works already when renaming the file to "libcom.fiskaly.client-darwin-amd64-v1.2.000.dylib.dylib". But still, strange Java logic.
