### ISSUE TITLE
Question regarding configuration of HTTP proxy

### ISSUE THREAD

**Issue by ceari** [fiskaly/fiskaly-sdk-java#19]
Hi,

Our JVM based POS software uses the Fiskaly Client. The JVM process is started with environment variables such as `http_proxy` and `https_proxy`, pointing to an HTTP proxy. We do not want to use this proxy for the Fiskaly client. However, when I use the Fiskaly client configuration API (https://developer.fiskaly.com/en/docs/client-documentation/#configuration) and set `http_proxy` to an empty string, the Fiskaly client still seems to use the proxy from the environment variables.
When I set `http_proxy` to some non-empty string, the Fiskaly client does attempt to use the proxy I set.
Only when I remove the environment variables `http_proxy` and `https_proxy` the client does no longer use the proxy.

Am I right in assuming that an empty `http_proxy` string leads the client to fall back on the environment variables for the proxy? Is there an option to tell the client to ignore the environment variables?

Thank you,
Daniel Diepold

**Comment by prempador** [comment]
Hi @ceari , 

Your assumption is right, yes. There is currently no option to cancel the fallback. We will work it into our Backlog. 

Thanks, 
@prempador

**Comment by ceari** [comment]
Hi @prempador,

thank you for the fast response. I also just thought of adding `kassensichv.io` to the `no_proxy` environment variable which the client seems to take into consideration.
