### ISSUE TITLE
Random segmentation faults

### ISSUE THREAD

**Issue by ceari** [fiskaly/fiskaly-sdk-java#2]
Hello, I'm getting random JVM segmentation faults when using this client in version 1.1.301-jre with com.fiskaly.client-linux-amd64-v1.1.300.so:

This happens constantly when running `FiskalyHttpClientTest#requestBasic` with OpenJDK 11 and less often but still occasionally when using OpenJDK 8:

```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fc2303f47d8, pid=2233, tid=2260
#
# JRE version: OpenJDK Runtime Environment (11.0.6+10) (build 11.0.6+10-post-Ubuntu-1ubuntu119.10.1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.6+10-post-Ubuntu-1ubuntu119.10.1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# J 405 c2 java.lang.String.hashCode()I java.base@11.0.6 (49 bytes) @ 0x00007fc2303f47d8 [0x00007fc2303f4620+0x00000000000001b8]
```

When I remove `Native.setProtected(true);` from `ClientLibrary.java` it seems to run stable without JVM crashes.

Please let me know if you need further information such as the JVM error report file.

**Comment by pgaubatz** [comment]
Hi @ceari! Thanks for reporting this issue and providing a potential fix for it. We'll try to find out the root cause of the crashes and keep you posted on this issue...
