### ISSUE TITLE
Problem Activation Live-Env

### ISSUE THREAD

**Issue by cjaentsch** [fiskaly/fiskaly-sdk-java#21]
As the support (complaint@) is not answering since yesterday (I thought P2 is answered in 30mins?), I'll try my luck here... (sorry text is in German).

> Wir haben gerade das Problem, dass wir für Managed-Accounts nicht die Live-Env aktivieren können:
> 
> Beispiel:
> POST organizations/xxxxxxxxxxxxxx/enable-env
> {"env":"LIVE"}
> 
> Wir bekommen folgenden Fehler (hier als PHP Objekt gerendert):
> 
> {
>   [&quot;status_code&quot;] =&gt; int(501)
>   [&quot;error&quot;] =&gt; string(15) &quot;Not Implemented&quot;
>   [&quot;code&quot;] =&gt; string(17) &quot;E_NOT_IMPLEMENTED&quot;
>   [&quot;message&quot;] =&gt; string(21) &quot;Internal Server Error&quot;
> }
> 
> Bis gestern hat die gleiche Anfrage (bei anderen Managed-Accounts) gut funktioniert. Wir haben nichts an unserer Anfrage geändert.
> Es betrifft alle Kunden, die gerade ihren Account im Live-Modus aktivieren wollen. Durch den Fehler ist es für diese Kunden leider nicht möglich, die TSE zu nutzen.
> 
> Könntet ihr mal schauen, was das sein kann?

**Comment by prempador** [comment]
Hello @cjaentsch , 

I will forward your request as soon as possible. Sorry for the inconvenience. 

Best @prempador

**Comment by prempador** [comment]
Just to make sure, 
- You said that it worked yesterday but doesn't work today.
- Are you sure the organization above those managed organizations is live?

**Comment by cjaentsch** [comment]
It worked until the day before yesterday (checked for more than 2 weeks). Since yesterday we receive this error. The superior organization has the live mode active.

**Comment by prempador** [comment]
Issue is resolved, you should also receive an email from us in the next few minutes.
