### ISSUE TITLE
Seems to be API documentation is outdated. 

### ISSUE THREAD

**Issue by hexwit** [fiskaly/fiskaly-sdk-java#25]
It is like api doc at https://developer.fiskaly.com/api/management/v0/#operation/createOrganization is not corresponding to the response payload. 

I got 'created_by_user' field in response, however I don't see this field in the documentation. 

Could you please check it?

**Comment by lumio** [comment]
Thank you for reporting this. You are right, the `created_by_user` field is indeed not documented.
We will add this to the specification soon.

**Comment by hexwit** [comment]
The same problem in POST https://dashboard.fiskaly.com/api/v0/organizations/{organization_id}/api-keys.

**Comment by lumio** [comment]
We added the missing `created_by_user` fields to the API spec. Thanks again for reporting this.
