### ISSUE TITLE
How to obtain new access token? No api endpoint available.

### ISSUE THREAD

**Issue by hexwit** [fiskaly/fiskaly-sdk-java#26]
Hello,

I have few question regarding api.

Precondition:
After successful authentication at https://kassensichv.io/api/v1/auth I got following response: 
`
{
  "access_token": "eyJhbGci......H7BwJ8RztZtgQ",
  "access_token_expires_in": 36000,
  "access_token_expires_at": 1601679867,
  "refresh_token": "eyJhbG........4O_z3PvreZpGR6hvbA",
  "refresh_token_expires_in": 1800,
  "refresh_token_expires_at": 1601645667
}
`

1. What token should be used for authenticating other requests: access or refresh? 
Usually access token is used, but here I am confused, because refresh token has expiration time less than access token.
Is this made by mistake or I misunderstand something?

2. How can I obtain new token when these ones expire? 
I don't see any API endpoint for getting new token. Should I just authenticate again?

3. Does fiskaly client handle token expiration?

Thanks.

**Comment by prempador** [comment]
If you are using the fiskaly Client (which you have to) with the fiskaly-sdk-java (which is optional) there is no need for you to do the authentication yourself. The fiskaly Client will handle the authentication, refreshing of the authentication etc.

From the fiskaly Client documentation: 

> Depending on the authentication method you want to use, either API-Key or email and password (latter only usable for the management API), you will need to provide the needed params. This will be either api_key and api_secret or email and password. You can also add all of the mentioned params. The client will prioritize authentication via email if the base_url is for the management API. Otherwise it will always use api_key and api_secret.

(https://developer.fiskaly.com/en/docs/client-documentation)
