### ISSUE TITLE
Missing enum types for payment_type

### ISSUE THREAD

**Issue by cjaentsch** [fiskaly/fiskaly-sdk-java#5]
Currently only the types "CASH" and "NON_CASH" are allowed as value for payment_type. DSFinV-K allows more types such as "DEBIT_CARD", "CREDIT_CARD", "PREPAID_CARD", "PAYMENT_SERVICE_PROVIDER" and "NONE". Do you plan to include those as well? Currently we transform all not "CASH" transactions to "NON_CASH" before submitting to the TSE, but it could be more precise as we actually have more precise data.

**Comment by prempador** [comment]
Hello @cjaentsch,

Thank you for your submission. 

The TSS only has to differentiate between CASH and NON_CASH. This is the reason why these are the only two types available. 

There will be another schema in the future that will have the other types you mentioned above.
