### ISSUE TITLE
API for client configuration

### ISSUE THREAD

**Issue by ceari** [fiskaly/fiskaly-sdk-java#8]
In the current Java API there doesn't seem to be a simple way to customize the client settings as described in https://developer.fiskaly.com/en/docs/client-documentation#3-add-custom-settings

Since the "context" is a `private` field in `FiskalyHttpClient` it also isn't straight forward to implement the JSON RPC call myself. I am able to work around this issue for now by accessing the private context field via reflection but it would be more elegant to have a proper API for configuration.

**Comment by prempador** [comment]
Hello @ceari, 

thanks for reporting this issue. We are currently working on adding all features from the fiskaly Client into the Java SDK (as it was done in the other SDKs). 

We will come back to you as soon as we are rolling out the missing features.
